<?php

namespace Jawabkom\Backend\Module\Profile\Test\Unit;

use Jawabkom\Backend\Module\Profile\Contract\Facade\ISearchByEmailFacade;
use Jawabkom\Backend\Module\Profile\Test\AbstractTestCase;
use Jawabkom\Backend\Module\Profile\Test\Classes\DI;

class SearchByEmailFacadeTest extends AbstractTestCase
{
    private DI $di;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->di = new DI();
    }

    public function testSearchEmailFacadeOffline(){
        $emailFacade = $this->di->make(ISearchByEmailFacade::class);

        $emailFacade->searchByEmail('');
    }

}